/*
 * Copyright (c) 2026  GeorgH93
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Type definitions for the Z.AI Image API.
 * Based on the official Z.AI API documentation.
 */

// ============================================
// Image Generation Request Types
// ============================================

export interface CreateImageRequest {
  /** Model code */
  model: 'glm-image' | 'cogview-4-250304';
  /** Text description of the image to generate */
  prompt: string;
  /** Image size (e.g., "1280x1280") */
  size?: string;
  /** Quality level: "hd" or "standard" */
  quality?: 'hd' | 'standard';
  /** Unique end user ID (6-128 characters) */
  user_id?: string;
}

export interface AsyncCreateImageRequest {
  /** Model code (only glm-image supported for async) */
  model: 'glm-image';
  /** Text description of the image to generate */
  prompt: string;
  /** Image size (e.g., "1280x1280") */
  size?: string;
  /** Quality level: "hd" only for async */
  quality?: 'hd';
  /** Unique end user ID (6-128 characters) */
  user_id?: string;
}

// ============================================
// Image Generation Response Types
// ============================================

export interface ImageData {
  /** Image URL (expires after 30 days) */
  url: string;
}

export interface ContentFilter {
  /** Safety enforcement stage */
  role: 'assistant' | 'user' | 'history';
  /** Severity level (0-3, 0 is most severe) */
  level: number;
}

export interface ImageGenerationResponse {
  /** Request creation time (Unix timestamp in seconds) */
  created: number;
  /** Array containing generated image data */
  data: ImageData[];
  /** Content safety information */
  content_filter?: ContentFilter[];
}

// ============================================
// Async Response Types
// ============================================

export interface AsyncResponse {
  /** Model name used */
  model: string;
  /** Task order number (use to query result) */
  id: string;
  /** Task number from client or generated by platform */
  request_id: string;
  /** Processing status */
  task_status: 'PROCESSING' | 'SUCCESS' | 'FAIL';
}

export interface AsyncImageGenerationResponse {
  /** Model name */
  model?: string;
  /** Processing status */
  task_status: 'PROCESSING' | 'SUCCESS' | 'FAIL';
  /** Task number */
  request_id?: string;
  /** Image generation results */
  image_result?: ImageData[];
  /** Error information if failed */
  error?: ApiError;
}

// ============================================
// Error Types
// ============================================

export interface ApiError {
  /** Error code */
  code: number;
  /** Error message */
  message: string;
}

export interface ErrorResponse {
  /** Error details */
  error: ApiError;
}

// ============================================
// API Client Types
// ============================================

export interface ZaiClient {
  /** Generate image synchronously */
  generateImage(request: CreateImageRequest): Promise<ImageGenerationResponse>;
  /** Generate image asynchronously */
  generateImageAsync(request: AsyncCreateImageRequest): Promise<AsyncResponse>;
  /** Get async image task result */
  getAsyncResult(taskId: string): Promise<AsyncImageGenerationResponse>;
  /** Generate video asynchronously */
  generateVideo(request: CreateVideoRequest): Promise<VideoResponse>;
  /** Get async video task result */
  getVideoResult(taskId: string): Promise<AsyncVideoGenerationResponse>;
}

export interface ClientOptions {
  /** API key */
  apiKey: string;
  /** Base URL */
  baseUrl?: string;
  /** Request timeout in ms */
  timeout?: number;
  /** Max retry attempts */
  maxRetries?: number;
  /** Initial retry delay in ms */
  retryDelay?: number;
}

// ============================================
// Video Generation Request Types
// ============================================

/** Video generation model codes */
export type VideoModel =
  | 'cogvideox-3'
  | 'viduq1-text'
  | 'viduq1-image'
  | 'viduq1-start-end'
  | 'vidu2-image'
  | 'vidu2-start-end'
  | 'vidu2-reference';

/** Base interface for all video generation requests */
export interface BaseVideoRequest {
  /** Unique end user ID (6-128 characters) */
  user_id?: string;
  /** Client-provided unique request identifier */
  request_id?: string;
}

/** CogVideoX-3 video generation request */
export interface CogVideoX3Request extends BaseVideoRequest {
  /** Model code */
  model: 'cogvideox-3';
  /** Text description of the video (max 512 characters) */
  prompt?: string;
  /** Output mode: quality (higher quality) or speed (faster) */
  quality?: 'quality' | 'speed';
  /** Whether to generate AI sound effects */
  with_audio?: boolean;
  /** Image URL(s) for image-to-video or start-end frame generation */
  image_url?: string | string[];
  /** Video resolution */
  size?: '1280x720' | '720x1280' | '1024x1024' | '1920x1080' | '1080x1920' | '2048x1080' | '3840x2160';
  /** Video frame rate: 30 or 60 */
  fps?: 30 | 60;
  /** Video duration in seconds: 5 or 10 */
  duration?: 5 | 10;
}

/** Vidu Q1 text-to-video request */
export interface ViduQ1TextRequest extends BaseVideoRequest {
  /** Model code */
  model: 'viduq1-text';
  /** Text description of the video (max 512 characters) */
  prompt: string;
  /** Style: general or anime */
  style?: 'general' | 'anime';
  /** Video duration in seconds (fixed at 5) */
  duration?: 5;
  /** Aspect ratio */
  aspect_ratio?: '16:9' | '9:16' | '1:1';
  /** Video resolution */
  size?: '1920x1080';
  /** Motion amplitude */
  movement_amplitude?: 'auto' | 'small' | 'medium' | 'large';
}

/** Vidu Q1 image-to-video request */
export interface ViduQ1ImageRequest extends BaseVideoRequest {
  /** Model code */
  model: 'viduq1-image';
  /** Text description of the video (max 512 characters) */
  prompt?: string;
  /** Source image URL or base64 */
  image_url: string;
  /** Video duration in seconds (fixed at 5) */
  duration?: 5;
  /** Video resolution */
  size?: '1920x1080';
  /** Motion amplitude */
  movement_amplitude?: 'auto' | 'small' | 'medium' | 'large';
}

/** Vidu Q1 start-end frame request */
export interface ViduQ1StartEndRequest extends BaseVideoRequest {
  /** Model code */
  model: 'viduq1-start-end';
  /** Text description of the video (max 512 characters) */
  prompt?: string;
  /** Array of two image URLs: [first_frame, last_frame] */
  image_url: [string, string];
  /** Video duration in seconds (fixed at 5) */
  duration?: 5;
  /** Video resolution */
  size?: '1920x1080';
  /** Motion amplitude */
  movement_amplitude?: 'auto' | 'small' | 'medium' | 'large';
}

/** Vidu 2 image-to-video request */
export interface Vidu2ImageRequest extends BaseVideoRequest {
  /** Model code */
  model: 'vidu2-image';
  /** Text description of the video (max 512 characters) */
  prompt?: string;
  /** Source image URL or base64 */
  image_url: string;
  /** Video duration in seconds (fixed at 4) */
  duration?: 4;
  /** Video resolution */
  size?: '1280x720';
  /** Motion amplitude */
  movement_amplitude?: 'auto' | 'small' | 'medium' | 'large';
  /** Whether to add background music */
  with_audio?: boolean;
}

/** Vidu 2 start-end frame request */
export interface Vidu2StartEndRequest extends BaseVideoRequest {
  /** Model code */
  model: 'vidu2-start-end';
  /** Text description of the video (max 512 characters) */
  prompt?: string;
  /** Array of two image URLs: [first_frame, last_frame] */
  image_url: [string, string];
  /** Video duration in seconds (fixed at 4) */
  duration?: 4;
  /** Video resolution */
  size?: '1280x720';
  /** Motion amplitude */
  movement_amplitude?: 'auto' | 'small' | 'medium' | 'large';
  /** Whether to add background music */
  with_audio?: boolean;
}

/** Vidu 2 reference-based video request */
export interface Vidu2ReferenceRequest extends BaseVideoRequest {
  /** Model code */
  model: 'vidu2-reference';
  /** Text description of the video (max 512 characters) */
  prompt?: string;
  /** Array of 1-3 reference image URLs */
  image_url: string[];
  /** Video duration in seconds (fixed at 4) */
  duration?: 4;
  /** Aspect ratio */
  aspect_ratio?: '16:9' | '9:16' | '1:1';
  /** Video resolution */
  size?: '1280x720';
  /** Motion amplitude */
  movement_amplitude?: 'auto' | 'small' | 'medium' | 'large';
  /** Whether to add background music */
  with_audio?: boolean;
}

/** Union type for all video generation requests */
export type CreateVideoRequest =
  | CogVideoX3Request
  | ViduQ1TextRequest
  | ViduQ1ImageRequest
  | ViduQ1StartEndRequest
  | Vidu2ImageRequest
  | Vidu2StartEndRequest
  | Vidu2ReferenceRequest;

// ============================================
// Video Generation Response Types
// ============================================

/** Video generation async response (returned immediately after request) */
export interface VideoResponse {
  /** Model name used in this call */
  model: string;
  /** Task order number (use to query result) */
  id: string;
  /** Task number from client or generated by platform */
  request_id: string;
  /** Processing status */
  task_status: 'PROCESSING' | 'SUCCESS' | 'FAIL';
}

/** Video data in async result */
export interface VideoData {
  /** Video URL */
  url: string;
}

/** Async video generation result (retrieved via task ID) */
export interface AsyncVideoGenerationResponse {
  /** Model name */
  model?: string;
  /** Processing status */
  task_status: 'PROCESSING' | 'SUCCESS' | 'FAIL';
  /** Task number */
  request_id?: string;
  /** Video generation results */
  video_result?: VideoData[];
  /** Error information if failed */
  error?: ApiError;
}
