/*
 * Copyright (c) 2026  GeorgH93
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Type definitions for the Z.AI Image API.
 * Based on the official Z.AI API documentation.
 */

// ============================================
// Image Generation Request Types
// ============================================

export interface CreateImageRequest {
  /** Model code */
  model: 'glm-image' | 'cogview-4-250304';
  /** Text description of the image to generate */
  prompt: string;
  /** Image size (e.g., "1280x1280") */
  size?: string;
  /** Quality level: "hd" or "standard" */
  quality?: 'hd' | 'standard';
  /** Unique end user ID (6-128 characters) */
  user_id?: string;
}

export interface AsyncCreateImageRequest {
  /** Model code (only glm-image supported for async) */
  model: 'glm-image';
  /** Text description of the image to generate */
  prompt: string;
  /** Image size (e.g., "1280x1280") */
  size?: string;
  /** Quality level: "hd" only for async */
  quality?: 'hd';
  /** Unique end user ID (6-128 characters) */
  user_id?: string;
}

// ============================================
// Image Generation Response Types
// ============================================

export interface ImageData {
  /** Image URL (expires after 30 days) */
  url: string;
}

export interface ContentFilter {
  /** Safety enforcement stage */
  role: 'assistant' | 'user' | 'history';
  /** Severity level (0-3, 0 is most severe) */
  level: number;
}

export interface ImageGenerationResponse {
  /** Request creation time (Unix timestamp in seconds) */
  created: number;
  /** Array containing generated image data */
  data: ImageData[];
  /** Content safety information */
  content_filter?: ContentFilter[];
}

// ============================================
// Async Response Types
// ============================================

export interface AsyncResponse {
  /** Model name used */
  model: string;
  /** Task order number (use to query result) */
  id: string;
  /** Task number from client or generated by platform */
  request_id: string;
  /** Processing status */
  task_status: 'PROCESSING' | 'SUCCESS' | 'FAIL';
}

export interface AsyncImageGenerationResponse {
  /** Model name */
  model?: string;
  /** Processing status */
  task_status: 'PROCESSING' | 'SUCCESS' | 'FAIL';
  /** Task number */
  request_id?: string;
  /** Image generation results */
  image_result?: ImageData[];
  /** Error information if failed */
  error?: ApiError;
}

// ============================================
// Error Types
// ============================================

export interface ApiError {
  /** Error code */
  code: number;
  /** Error message */
  message: string;
}

export interface ErrorResponse {
  /** Error details */
  error: ApiError;
}

// ============================================
// API Client Types
// ============================================

export interface ZaiClient {
  /** Generate image synchronously */
  generateImage(request: CreateImageRequest): Promise<ImageGenerationResponse>;
  /** Generate image asynchronously */
  generateImageAsync(request: AsyncCreateImageRequest): Promise<AsyncResponse>;
  /** Get async task result */
  getAsyncResult(taskId: string): Promise<AsyncImageGenerationResponse>;
}

export interface ClientOptions {
  /** API key */
  apiKey: string;
  /** Base URL */
  baseUrl?: string;
  /** Request timeout in ms */
  timeout?: number;
  /** Max retry attempts */
  maxRetries?: number;
  /** Initial retry delay in ms */
  retryDelay?: number;
}
